# Generated by Django 6.1 on 2026-09-01 21:04

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stale_after_days', models.PositiveSmallIntegerField(default=accounts.models.default_stale_after_days, help_text='Au-delà, une candidature envoyée remonte dans « À traiter maintenant ».', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='sans nouvelles après (jours)')),
                ('follow_up_days', models.PositiveSmallIntegerField(default=accounts.models.default_follow_up_days, help_text="Délai entre l'envoi d'une candidature et la relance programmée.", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='relance proposée à (jours)')),
                ('search_radius_km', models.PositiveSmallIntegerField(default=accounts.models.default_search_radius_km, help_text='Autour de ton point de départ.', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)], verbose_name='rayon de recherche (km)')),
                ('default_cv_language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], default='fr', max_length=2, verbose_name='langue de CV par défaut')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'préférences',
                'verbose_name_plural': 'préférences',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120, verbose_name='nom affiché')),
                ('headline', models.CharField(blank=True, help_text='Ce que tu cherches, en une ligne : « Ingénieur DevOps senior ».', max_length=200, verbose_name='titre professionnel')),
                ('location', models.CharField(blank=True, help_text="La ville d'où se comptent les distances des offres.", max_length=200, verbose_name='point de départ')),
                ('onboarded_at', models.DateTimeField(blank=True, null=True, verbose_name='profil complété le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil',
                'verbose_name_plural': 'profils',
            },
        ),
    ]
