# Generated by Django 6.1 on 2026-09-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text="Facultatif. Sert d'en-tête aux CV qu'une extension rédige, et l'anonymisation le masque partout ailleurs.", max_length=60, verbose_name='téléphone'),
        ),
    ]
