# Generated by Django 6.1 on 2026-09-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, help_text='Fin de la période payée. Sans date ou après expiration, le compte est gratuit.', null=True, verbose_name="premium jusqu'au"),
        ),
    ]
