# Generated by Django 6.1 on 2026-09-09 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_premium_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(blank=True, choices=[('unemployed_urgent', 'Sans emploi, il me faut un poste rapidement'), ('unemployed_exploring', "Sans emploi, je prends le temps d'explorer"), ('employed_ready', 'En poste, prêt·e à changer'), ('employed_open', "En poste, à l'écoute du marché")], max_length=24, verbose_name='situation')),
                ('ai_tools_used', models.CharField(blank=True, choices=[('yes', 'Oui'), ('no', 'Non'), ('not_sure', 'Pas vraiment')], max_length=12, verbose_name="outils d'IA déjà essayés")),
                ('challenge', models.CharField(blank=True, choices=[('no_reply', "Je postule, mais je n'ai presque jamais de réponse"), ('too_slow', 'Postuler me prend trop de temps'), ('poor_fit', 'Difficile de trouver des offres qui me correspondent vraiment'), ('lost', 'Je ne sais pas par où commencer')], max_length=12, verbose_name='principale difficulté')),
                ('help_wanted', models.JSONField(blank=True, default=list, verbose_name='attentes')),
                ('job_titles', models.JSONField(blank=True, default=list, verbose_name='postes visés')),
                ('industries', models.JSONField(blank=True, default=list, verbose_name='secteurs')),
                ('any_industry', models.BooleanField(default=False, verbose_name='tous secteurs')),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Débutant·e'), ('mid', 'Confirmé·e'), ('senior', 'Senior'), ('lead', 'Direction'), ('unsure', 'Je ne sais pas trop')], max_length=8, verbose_name="niveau d'expérience")),
                ('education_level', models.CharField(blank=True, choices=[('none', 'Sans diplôme particulier'), ('secondary', 'Secondaire (CESS)'), ('vocational', 'Formation professionnelle ou graduat'), ('bachelor', 'Bachelier'), ('master', 'Master ou plus')], max_length=12, verbose_name='formation')),
                ('work_types', models.JSONField(blank=True, default=list, verbose_name='types de contrat')),
                ('work_mode', models.CharField(choices=[('on_site', 'Sur site'), ('hybrid', 'Hybride'), ('remote', 'Télétravail'), ('unknown', 'Non précisé')], default='unknown', max_length=10, verbose_name='mode de travail')),
                ('cities', models.JSONField(blank=True, default=list, verbose_name='villes')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='salaire minimum (EUR brut)')),
                ('salary_period', models.CharField(blank=True, choices=[('hour', 'Par heure'), ('month', 'Par mois'), ('year', 'Par an')], max_length=6, verbose_name='période du salaire')),
                ('start_timeline', models.CharField(blank=True, choices=[('asap', 'Dès que possible'), ('one_to_three_months', 'Dans les 1 à 3 mois'), ('open', 'Quand la bonne occasion se présente')], max_length=20, verbose_name='horizon de départ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profil de recherche',
                'verbose_name_plural': 'profils de recherche',
            },
        ),
    ]
