# Generated by Django 6.1 on 2026-09-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_phone_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_level',
            field=models.CharField(choices=[('automatic', 'Automatique'), ('free', 'Gratuit'), ('premium', 'Premium')], default='automatic', help_text="Automatique : Premium en mode local hors SaaS, sinon gratuit sans période payée. Gratuit désactive Premium ; Premium l'active jusqu'à la date éventuelle ci-dessous.", max_length=12, verbose_name="niveau d'abonnement"),
        ),
        migrations.AlterField(
            model_name='profile',
            name='premium_until',
            field=models.DateTimeField(blank=True, help_text="Date limite de l'accès Premium. Après expiration, le compte est gratuit. Sans date, le niveau choisi s'applique sans limite de durée.", null=True, verbose_name="premium jusqu'au"),
        ),
    ]
