# Generated by Django 6.1 on 2026-09-14 09:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from rls.operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_launch_interest'),
        ('rls', '0002_search_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchEmailJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('welcome', 'E-mail de bienvenue'), ('contact_sync', 'Contact Brevo')], max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium')], max_length=12)),
                ('consent_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('retry', 'Nouvel essai prévu'), ('succeeded', 'Terminé'), ('failed', 'À corriger'), ('uncertain', 'Envoi à vérifier'), ('suppressed', 'Désinscription respectée'), ('cancelled', 'Annulé')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('lease_until', models.DateTimeField(blank=True, null=True)),
                ('claim_token', models.UUIDField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('task_id', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_email_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traitement e-mail',
                'verbose_name_plural': 'traitements e-mail',
                'indexes': [models.Index(fields=['user', 'status', 'next_attempt_at'], name='launch_email_due_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'kind'), name='one_launch_email_job_per_kind')],
            },
        ),
        EnableRowLevelSecurity('accounts.LaunchEmailJob', owner='user'),
    ]
