# Generated by Django 6.1 on 2026-09-14 21:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models
from django.contrib.auth.hashers import make_password
from rls.operations import EnableRowLevelSecurity


def remove_production_passwords(apps, schema_editor):
    if settings.AUTH_MODE != "accounts" or not (settings.PASSWORDLESS_AUTH or settings.IS_SAAS_PRODUCTION):
        return
    User = apps.get_model(settings.AUTH_USER_MODEL)
    # The deployment's maintenance connection applies this migration. No
    # address is marked verified: each existing account must prove ownership.
    User.objects.using(schema_editor.connection.alias).exclude(password__startswith="!").update(password=make_password(None))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_launchemailjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.CreateModel(
            name='EmailLinkRateLimit',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSignInLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('signup', 'Inscription'), ('login', 'Connexion'), ('change', "Changement d'e-mail")], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('original_email', models.EmailField(blank=True, max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('onboarding_data', models.JSONField(blank=True, default=dict)),
                ('next_path', models.CharField(blank=True, max_length=2048)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sending_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        EnableRowLevelSecurity('accounts.EmailSignInLink', owner='user', unbound_visible=True),
        EnableRowLevelSecurity('accounts.EmailLinkRateLimit', owner='user', unbound_visible=True),
        migrations.RunPython(remove_production_passwords, migrations.RunPython.noop),
    ]
