# Generated by Django 6.1 on 2026-08-31 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200, verbose_name='libellé')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='langue')),
                ('is_primary', models.BooleanField(default=False, verbose_name='profil principal')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='nom complet')),
                ('headline', models.CharField(blank=True, max_length=250, verbose_name='titre professionnel')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='téléphone')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='localisation')),
                ('links', models.JSONField(blank=True, default=list, verbose_name='liens')),
                ('summary', models.TextField(blank=True, verbose_name='résumé')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='compétences')),
                ('experiences', models.JSONField(blank=True, default=list, verbose_name='expériences')),
                ('education', models.JSONField(blank=True, default=list, verbose_name='formation')),
                ('languages', models.JSONField(blank=True, default=list, verbose_name='langues')),
                ('certifications', models.JSONField(blank=True, default=list, verbose_name='certifications')),
                ('extras', models.JSONField(blank=True, default=list, verbose_name='divers')),
                ('raw_text', models.TextField(blank=True, verbose_name='texte source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_profiles', to='tracker.document', verbose_name="document d'origine")),
            ],
            options={
                'verbose_name': 'profil candidat',
                'verbose_name_plural': 'profils candidats',
                'ordering': ['-is_primary', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('parse_cv', 'Analyse de CV'), ('match', 'Évaluation de compatibilité'), ('generate_cv', 'Génération de CV'), ('scout', "Veille d'offres")], max_length=20, verbose_name='type')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('succeeded', 'Terminée'), ('failed', 'Échouée')], db_index=True, default='pending', max_length=10, verbose_name='état')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='paramètres')),
                ('result', models.JSONField(blank=True, default=dict, verbose_name='résultat')),
                ('error', models.TextField(blank=True, verbose_name='erreur')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('input_tokens', models.PositiveIntegerField(default=0, verbose_name="jetons d'entrée")),
                ('output_tokens', models.PositiveIntegerField(default=0, verbose_name='jetons de sortie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='démarrée le')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='terminée le')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_runs', to='tracker.application', verbose_name='candidature')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='jobhunt_ai.candidateprofile', verbose_name='profil')),
            ],
            options={
                'verbose_name': "exécution d'agent",
                'verbose_name_plural': "exécutions d'agents",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='langue')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='contenu')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_cvs', to='tracker.application', verbose_name='candidature')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generated_cvs', to='tracker.document', verbose_name='document')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cvs', to='jobhunt_ai.candidateprofile', verbose_name='profil')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cvs', to='jobhunt_ai.agentrun', verbose_name='exécution')),
            ],
            options={
                'verbose_name': 'CV généré',
                'verbose_name_plural': 'CV générés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='compatibilité (%)')),
                ('summary', models.TextField(blank=True, verbose_name='verdict')),
                ('strengths', models.TextField(blank=True, verbose_name='ce qui joue pour toi')),
                ('weaknesses', models.TextField(blank=True, verbose_name='ce qui joue contre toi')),
                ('strategy', models.TextField(blank=True, verbose_name='comment aborder cette candidature')),
                ('matched_skills', models.JSONField(blank=True, default=list, verbose_name='compétences couvertes')),
                ('partial_skills', models.JSONField(blank=True, default=list, verbose_name='compétences partielles')),
                ('missing_skills', models.JSONField(blank=True, default=list, verbose_name='compétences manquantes')),
                ('gaps', models.JSONField(blank=True, default=list, verbose_name='lacunes')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='modèle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_match_reports', to='tracker.application', verbose_name='candidature')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reports', to='jobhunt_ai.candidateprofile', verbose_name='profil')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_reports', to='jobhunt_ai.agentrun', verbose_name='exécution')),
            ],
            options={
                'verbose_name': 'rapport de compatibilité',
                'verbose_name_plural': 'rapports de compatibilité',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'À trier'), ('imported', 'Importée'), ('dismissed', 'Écartée')], db_index=True, default='new', max_length=10, verbose_name='état')),
                ('title', models.CharField(max_length=250, verbose_name='intitulé')),
                ('company_name', models.CharField(max_length=200, verbose_name='société')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='lien')),
                ('source_name', models.CharField(blank=True, max_length=100, verbose_name='source')),
                ('published_on', models.DateField(blank=True, null=True, verbose_name='publiée le')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('language', models.CharField(blank=True, max_length=2, verbose_name='langue')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='compatibilité (%)')),
                ('score_reason', models.TextField(blank=True, verbose_name='justification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_leads', to='tracker.application', verbose_name='candidature créée')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='jobhunt_ai.agentrun', verbose_name='exécution')),
            ],
            options={
                'verbose_name': "piste d'offre",
                'verbose_name_plural': "pistes d'offres",
                'ordering': ['-score', '-created_at'],
            },
        ),
    ]
