# Generated by Django 6.1 on 2026-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='qualifications',
            field=models.JSONField(blank=True, default=dict, verbose_name='grille de qualifications'),
        ),
        migrations.AddField(
            model_name='offerlead',
            name='score_blockers',
            field=models.JSONField(blank=True, default=list, verbose_name='points bloquants'),
        ),
        migrations.AddField(
            model_name='offerlead',
            name='score_confidence',
            field=models.CharField(blank=True, max_length=20, verbose_name='fiabilité du pré-tri'),
        ),
        migrations.AlterField(
            model_name='offerlead',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='pré-tri (%)'),
        ),
    ]
