# Generated by Django 6.1 on 2026-09-05 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt_ai', '0006_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='deadline_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='phase',
            field=models.CharField(blank=True, max_length=100, verbose_name='étape'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='progress_current',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='progress_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['owner', 'status', 'kind', '-created_at'], name='ai_run_owner_state_kind_idx'),
        ),
    ]
