# Generated by Django 6.1 on 2026-09-05 08:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt_ai', '0007_agentrun_deadline_at_agentrun_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='fanout_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='fanout_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScoutTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('source', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scraping', 'Lecture'), ('scraped', 'À analyser'), ('analyzing', 'Analyse'), ('succeeded', 'Terminée'), ('failed', 'Échouée')], default='pending', max_length=10)),
                ('scraped_text', models.TextField(blank=True)),
                ('created_leads', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('deadline_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='jobhunt_ai.agentrun')),
            ],
            options={
                'indexes': [models.Index(fields=['run', 'status', 'deadline_at'], name='ai_target_state_deadline_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'key'), name='ai_target_run_key_uniq')],
            },
        ),
    ]
