# Generated by Django 6.1 on 2026-09-10 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from rls.operations import EnableRowLevelSecurity


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunt_ai', '0009_scout_target_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAIQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('requests', models.PositiveIntegerField(default=0)),
                ('minute_started_at', models.DateTimeField()),
                ('minute_requests', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quotas', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'month'), name='ai_quota_owner_month')],
            },
        ),
        EnableRowLevelSecurity('jobhunt_ai.UserAIQuota', owner='owner'),
    ]
