# Generated by Django 6.1 on 2026-08-31 17:05

import django.db.models.deletion
import django.utils.timezone
import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='intitulé du poste')),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('distance_km', models.PositiveSmallIntegerField(blank=True, help_text="À vol d'oiseau depuis Nivelles.", null=True, verbose_name='distance (km)')),
                ('work_mode', models.CharField(choices=[('on_site', 'Sur site'), ('hybrid', 'Hybride'), ('remote', 'Télétravail'), ('unknown', 'Non précisé')], default='unknown', max_length=10, verbose_name='mode de travail')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text="Estimation de recouvrement entre l'annonce et ton profil, de 0 à 100.", null=True, verbose_name='compatibilité (%)')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name="lien de l'offre")),
                ('cv_language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], default='fr', max_length=2, verbose_name='langue du CV')),
                ('status', models.CharField(choices=[('backlog', 'À examiner'), ('to_apply', 'À postuler'), ('sent', 'Candidature envoyée'), ('screening', 'Premier contact'), ('interview', 'Entretien'), ('technical', 'Test technique'), ('offer', 'Offre reçue'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('withdrawn', 'Retirée'), ('ghosted', 'Sans réponse'), ('discarded', 'Écartée')], db_index=True, default='backlog', max_length=20, verbose_name='statut')),
                ('discovered_on', models.DateField(blank=True, null=True, verbose_name='offre relevée le')),
                ('applied_on', models.DateField(blank=True, null=True, verbose_name='date de candidature')),
                ('follow_up_on', models.DateField(blank=True, null=True, verbose_name='relance prévue')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='clôturée le')),
                ('summary', models.TextField(blank=True, help_text="La phrase qui résume l'offre.", verbose_name='résumé')),
                ('strengths', models.TextField(blank=True, verbose_name='ce qui joue pour toi')),
                ('weaknesses', models.TextField(blank=True, verbose_name='ce qui joue contre toi')),
                ('strategy', models.TextField(blank=True, verbose_name='comment aborder cette candidature')),
                ('posting_raw', models.TextField(blank=True, verbose_name="texte de l'annonce")),
                ('notes_raw', models.TextField(blank=True, verbose_name="notes d'origine")),
                ('personal_notes', models.TextField(blank=True, verbose_name='mes notes')),
                ('discard_reason', models.TextField(blank=True, verbose_name="raison de l'écartement")),
                ('legacy_folder', models.CharField(blank=True, max_length=300, verbose_name="dossier d'origine")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'candidature',
                'verbose_name_plural': 'candidatures',
                'ordering': ['-score', 'company__name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='nom')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('sector', models.CharField(choices=[('private', 'Privé'), ('parapublic', 'Parapublic'), ('public', 'Public'), ('unknown', 'Non déterminé')], default='unknown', max_length=20, verbose_name='secteur')),
                ('website', models.URLField(blank=True, verbose_name='site web')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='localisation')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'société',
                'verbose_name_plural': 'sociétés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='plateforme')),
                ('url', models.URLField(blank=True, verbose_name='adresse')),
                ('searched_for', models.TextField(blank=True, verbose_name="ce que j'y ai cherché")),
                ('outcome', models.TextField(blank=True, verbose_name='résultat')),
                ('is_lead', models.BooleanField(default=False, help_text='Canal identifié mais pas encore exploré.', verbose_name='piste à explorer')),
                ('last_checked', models.DateField(blank=True, null=True, verbose_name='dernière consultation')),
            ],
            options={
                'verbose_name': 'plateforme',
                'verbose_name_plural': 'plateformes',
                'ordering': ['is_lead', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='compétence')),
                ('demand_count', models.PositiveSmallIntegerField(default=0, verbose_name='offres concernées')),
                ('demand_label', models.CharField(blank=True, max_length=120, verbose_name='libellé de fréquence')),
                ('why_it_matters', models.TextField(blank=True, verbose_name='pourquoi ça compte')),
                ('action_plan', models.TextField(blank=True, verbose_name='piste')),
                ('status', models.CharField(choices=[('todo', 'À travailler'), ('doing', 'En cours'), ('done', 'Comblée')], default='todo', max_length=10, verbose_name='état')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'lacune',
                'verbose_name_plural': 'lacunes',
                'ordering': ['position', '-demand_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='date')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('status', 'Changement de statut'), ('applied', 'Candidature envoyée'), ('follow_up', 'Relance'), ('email', 'E-mail'), ('call', 'Appel'), ('interview', 'Entretien'), ('test', 'Test technique'), ('offer', 'Offre'), ('rejection', 'Refus')], default='note', max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=250, verbose_name='intitulé')),
                ('detail', models.TextField(blank=True, verbose_name='détail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracker.application', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
                'ordering': ['-happened_on', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='tracker.company', verbose_name='société'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='fonction')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=60, verbose_name='téléphone')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tracker.application', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Lettre de motivation'), ('posting', 'Annonce'), ('portfolio', 'Portfolio'), ('other', 'Autre')], default='cv', max_length=20, verbose_name='type')),
                ('label', models.CharField(max_length=250, verbose_name='libellé')),
                ('file', models.FileField(max_length=400, upload_to=tracker.models.document_upload_to, verbose_name='fichier')),
                ('language', models.CharField(blank=True, choices=[('fr', 'Français'), ('en', 'Anglais'), ('nl', 'Néerlandais')], max_length=2, verbose_name='langue')),
                ('is_primary', models.BooleanField(default=False, verbose_name='document principal')),
                ('source_path', models.CharField(blank=True, max_length=500, verbose_name="chemin d'origine")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, help_text='Laisser vide pour un document de la bibliothèque (CV génériques).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tracker.application', verbose_name='candidature')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-is_primary', 'kind', 'label'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='source_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='tracker.platform', verbose_name='source'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'follow_up_on'], name='tracker_app_status_67f9f2_idx'),
        ),
    ]
