# Generated by Django 6.1 on 2026-09-01 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='platform',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platforms', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AddField(
            model_name='skillgap',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire'),
        ),
        migrations.AlterField(
            model_name='application',
            name='distance_km',
            field=models.PositiveSmallIntegerField(blank=True, help_text="À vol d'oiseau depuis chez toi.", null=True, verbose_name='distance (km)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=200, verbose_name='plateforme'),
        ),
        migrations.AlterField(
            model_name='skillgap',
            name='name',
            field=models.CharField(max_length=200, verbose_name='compétence'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='company_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='platform',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='platform_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='skillgap',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='skillgap_name_per_owner'),
        ),
    ]
