"""Slugs become unique per account, not globally.

The runtime role only sees the account's own rows (row-level security), so a
global uniqueness check could not be trusted; the upload path now carries the
account id to keep two accounts' identical slugs apart on disk.
"""

# Generated by Django 6.1 on 2026-09-02 23:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_owner_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, max_length=220),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='application_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='company_slug_per_owner'),
        ),
    ]
